[package]
name = "http_server_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
epoll = "4.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
polling = "3.7.4"
